data-axle/elastic_record

elastic_record.gemspec, lib/elastic_record/connection.rb, lib/elastic_record/index/documents.rb, test/elastic_record/connection_test.rb, test/elastic_record/log_subscriber_test.rb
Testing a script that creates 250,000 records (in bulk batches of 500) showed a significant speed increase (~62%).
=> Use Oj instead of ActiveSupport::JSON

Gemfile, README.rdoc, elastic_record.gemspec, lib/elastic_record.rb, lib/elastic_record/connection.rb, lib/elastic_record/index/deferred.rb, lib/elastic_record/index/documents.rb, lib/elastic_record/tasks/index.rake, test/elastic_record/connection_test.rb
This reverts the default JSON parser to `ActiveSupport::JSON`, and only uses Oj if:
1. `ElasticRecord.json_parser` is set to `:oj`
2. Oj is loaded
This should ease upgrading.
=> Use Oj optionally

Gemfile, elastic_record.gemspec, lib/elastic_record/relation/search_methods.rb, test/elastic_record/relation/search_methods_test.rb
Provides some ActiveRecord parity:
Find all widgets where color is not red:
`Widget.filter.not(color: 'red')`
Find all nested objects, avoiding the need to build a painful nested filter:
`Business.filter.nested('executives', 'executives.first_name' => 'Bob')`
@data-axle/developers
=> Add support for filter.not(color: 'red') and filter.nested('comments', 'comments.author' => 'Bob')

README.rdoc
It was not obvious how the `index:` rake tasks chose the indexes to handle, without digging through a few files.
=> Add docs about creating multiple indexes via rake

Gemfile, test/elastic_record/connection_test.rb, test/elastic_record/log_subscriber_test.rb, test/helper.rb
fakeweb hasn't been updated since 2010. Meanwhile, webmock has been fairly actively maintained (the last release was last month). The switchover was fairly trivial.
=> Replace fakeweb with webmock

README.md, elastic_record.gemspec, lib/elastic_record/index.rb, lib/elastic_record/relation.rb, lib/elastic_record/tasks/index.rake, test/dummy/.env.test, test/elastic_record/index_test.rb, test/elastic_record/relation_test.rb
To fetch documents without an additional request to a backing ActiveRecord database you can load the documents from `_source`.
```ruby
Product.elastic_index.loading_from_source do
Product.elastic_search.filter(name: "Pizza")
end
```
Use `elastic_index.load_from_source = true` to configure an index without ActiveRecord.
```ruby
class Product
include ActiveModel::Model
include ElasticRecord::Record
self.elastic_index.load_from_source = true
end
```
=> Add configuration to load documents from source

lib/elastic_record/index/documents.rb, test/dummy/app/models/warehouse.rb, test/elastic_record/index/documents_test.rb, test/elastic_record/relation_test.rb
ElasticSearch supports [automatically generating an ID for documents](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/docs-index_.html#_automatic_id_generation) where id is not specified. To automatically generate an id with ElasticSearch the document must be sent as a `POST` request to the index.
This adds a condition to `ElasticRecord::Index::Documents#index_document` which will `POST` a document to the index if no id is specified.
=> Support Automatic ID Generation

lib/elastic_record/index/documents.rb, test/elastic_record/relation/batches_test.rb
From the ES docs:
> _doc has no real use-case besides being the most efficient sort order. So if you don’t care about the order in which documents are returned, then you should sort by _doc. This especially helps when scrolling.
For DAX-3334, I care about the order and I don't want it overwritten with _doc.
=> Finding in batches respects sort if it was provided

lib/elastic_record/index/documents.rb, lib/elastic_record/relation.rb, lib/elastic_record/relation/batches.rb, lib/elastic_record/relation/hits.rb, test/elastic_record/relation/hits_test.rb, test/elastic_record/relation_test.rb
`Relation::Batch` was misbehaving with `Index#load_from_source`. This PR fixes two issues:
Problem 1:
When `load_from_source=false`, source was still being loaded. This makes things _slow_!
Problem 2:
When `load_from_source=true`, the code tried to call `AR.where`, rather than respecting the option to use source.
=> Support source options with batch methods

lib/elastic_record/as_document.rb, test/elastic_record/as_document_test.rb
Make symbols vs strings consistent; don't call as_search_document on Hashes
=> Object indexing fixups

lib/elastic_record/relation/hits.rb, lib/elastic_record/relation/search_methods.rb, lib/elastic_record/relation/value_methods.rb, test/dummy/app/models/project.rb, test/dummy/app/models/warehouse.rb, test/dummy/app/models/widget.rb, test/dummy/db/migrate/20151211225259_create_projects.rb, test/dummy/db/migrate/20180215140125_create_widgets.rb, test/dummy/db/schema.rb, test/elastic_record/as_document_test.rb, test/elastic_record/callbacks_test.rb, test/elastic_record/index/documents_test.rb, test/elastic_record/integration/active_record_test.rb, test/elastic_record/relation/batches_test.rb, test/elastic_record/relation/delegation_test.rb, test/elastic_record/relation/finder_methods_test.rb, test/elastic_record/relation/hits_test.rb, test/elastic_record/relation/search_methods_test.rb, test/elastic_record/relation_test.rb, test/helper.rb
This PR accomplishes two things:
* Adds support for `.includes`. This allows for `Widget.includes(:factory).filter(color: 'red')`, and the factory relationship will be preloaded.
* Replace "mock" Widget with a real `Widget` model that has a table. This allows for deeper testing and increases authenticity of tests.
TODO:
=> Support includes and use active record for testing

.travis.yml, lib/elastic_record/doctype.rb, lib/elastic_record/index/documents.rb, lib/elastic_record/index/manage.rb, lib/elastic_record/index/mapping.rb, lib/elastic_record/percolator_model.rb, test/elastic_record/doctype_test.rb, test/elastic_record/index/documents_test.rb, test/elastic_record/percolator_model_test.rb
The primary change here is how `mapping_body` behaves. Both ES5 and ES6 versions will now us a single doctype mapping strategy, regardless if multiple models were used to initialize the index. Since both versions support this, the approach alleviates the need have the `doctype.name` be dynamic depending on the ES version.
As an alternative, the mapping also adds a `custom_doctype` field to the mapping which would allow implementations to filter results by a doctype if multiple models share the same index. However, models are not automatically index with the `custom_doctype` set appropriately...I was struggling to get this working properly.
Ideally, I think we'd want something like this to be possible:
```ruby
ElasticRecord::Index.new([Widget, Product]).create_and_deploy
Widget.create …
```
=> [WIP] ES6 Compatibility Upgrade

lib/elastic_record/connection.rb, lib/elastic_record/index/deferred.rb, lib/elastic_record/index/documents.rb, test/elastic_record/index/documents_test.rb
This is mostly Matt's code but he went 🚵 
This fixes the case where you nest ElasticRecord bulk "transactions" and ActiveRecord transactions inside of itself, and there's an exception in the inner set of blocks. See the `test_bulk_nested` case for an example.
=> When nesting bulk blocks, always defer to the outermost one

.travis.yml, lib/elastic_record/as_document.rb, test/dummy/app/models/widget.rb, test/dummy/db/migrate/20180215140125_create_widgets.rb, test/dummy/db/schema.rb, test/elastic_record/as_document_test.rb, test/elastic_record/index/mapping_test.rb
Before:
Nested children used a method to define `as_search_document`. In our implementation, that returned everything that was indexed. Fine for most things, except the new range type.
Now:
Nested child objects don't need to implement `as_search_document`. This will automatically traverse the mappings and do the same thing as the parent document.
Any methods that override `as_search_document` need to be updated to take an argument, even if they choose to ignore it.
=> Nested mappings define as_search_document

lib/elastic_record/errors.rb, lib/elastic_record/index/documents.rb, test/elastic_record/index/documents_test.rb
Add `ExpiredScrollError` and `InvalidScrollError`.
=> Raise more specific errors when a scroll fails

lib/elastic_record/relation/hits.rb, test/elastic_record/relation/hits_test.rb
For some upcoming features, I would like to access the raw ES results.
It will help with:
1) Finding search scores
2) Getting the name of the query that matched
=> Expose methods for getting the raw results of a query

lib/elastic_record/relation/finder_methods.rb, test/elastic_record/relation/finder_methods_test.rb
1) Don't raise an error on Model.find([]) - ActiveRecord doesn't.
2) Override the default ES limit of 10 records when finding by IDs.
=> Fixes for find(ids)

README.md, lib/elastic_record/index.rb, lib/elastic_record/model.rb, lib/elastic_record/searching.rb, test/dummy/app/models/project.rb, test/elastic_record/index_test.rb, test/elastic_record/searching_test.rb
Simply `include ElasticRecord::LoadFromSource` in the model.
No need for models to set the flag manually. Enables `Model.first`,
`find` and friends for easy lookup.
=> Make it easier to store a model entirely in ES

lib/elastic_record/index/manage.rb, test/elastic_record/index/manage_test.rb
The previous code had the opposite behavior. The bug strangely manifested itself only when `ElasticRecord::Config.default_index_settings` was set.
Also, add a test for `setting_overrides`.
=> setting_overrides should override defaults

elastic_record.gemspec, lib/elastic_record/relation/search_methods.rb
Updated to change reference from `arelastic.query` to `arelastic.queries`.
=> Change Arelastic.query to Arelastic.queries

lib/elastic_record/config.rb, lib/elastic_record/index.rb, test/elastic_record/index_test.rb
It can be used to append "test" to the indexes and aliases so that one
ElasticSearch server can be used for tests and development.
=> Index suffix

lib/elastic_record/relation/batches.rb, test/elastic_record/relation/batches_test.rb
Adds a convenience method that yields `SearchHits` when scrolling.
=> Add find_hits_in_batches

lib/elastic_record/config.rb, lib/elastic_record/index/documents.rb, test/elastic_record/config_test.rb, test/elastic_record/index/documents_test.rb
After a batch operation (which largely use #each_slice) we should clear
the scroll by default to reduce the cost of these operations.
This implementation clears them all in 1 DELETE after yielding search results. You could probably delete as you go as well. More requests, but also cleans up sooner. I think this works, but I could see the argument for implementing that as well. Open for discussion.
=> Clear scroll after #each_slice

lib/elastic_record/as_document.rb, test/elastic_record/as_document_test.rb
Currently in elastic record attempts to clear nested fields (set them
to null) are dropped. To allow this, we need to allow specifically
provided (in the active record sense) fields to be submitted.
For example, if you had a nested field/object sub_widget on a widget, and tried to "clear" a field on subwidget by setting the value to nil, that update would be dropped from the update sent to ElasticSearch.
```ruby
widget = Widget.create(name: 'My Widget', sub_widget: SubWidget.new(sub_field: 'hi!'))
sub_widget = widget.sub_widget
sub_widget.sub_field = nil
widget.sub_widget = sub_widget
widget.save!
```
The resulting post wouldn't include sub_field, and this the old value would persist according to the source document in ElasticSearch.
This change corrects this problem.
=> Ensure provided nested object fields submit

lib/elastic_record/index.rb, lib/elastic_record/index/deferred.rb, lib/elastic_record/index/documents.rb, lib/elastic_record/index/search.rb, test/elastic_record/index/documents_test.rb, test/elastic_record/index/search_test.rb
Enables `Document.multi_search([query1, query2])`. Mirrors the `search` method above it.
=> multi_search support

lib/elastic_record/index.rb, lib/elastic_record/index/documents.rb, test/elastic_record/index/documents_test.rb
Deprecated/gone in 7+, not needed in 6. Since Data Axle is already not using and/or reliant on this, start stripping the rest of it out.
There's still some alternative uses that mapping_type serves for has_child queries and such, so I can't completely remove all of it as I'd like, but this will at least get rid of some observed ES7 deprecation warnings.
=> Remove type param/routing in indexing docs/search

lib/elastic_record/relation/hits.rb
ElasticSearch introduced a new feature where a search has the total
limited to 10k by default for all requests. While this might make sense
for some usages, elastic_record is designed to be an ORM. You wouldn't
expect a SQL COUNT to lie to you unless you gave it a magic word.
=> Ensure relations return full total of hits

.travis.yml, README.md, lib/elastic_record.rb, lib/elastic_record/config.rb, lib/elastic_record/elastic_connection.rb, lib/elastic_record/index.rb, lib/elastic_record/index/documents.rb, lib/elastic_record/index/manage.rb, lib/elastic_record/index/mapping_type.rb, lib/elastic_record/index/search.rb, lib/elastic_record/model.rb, lib/elastic_record/version.rb, test/dummy/app/models/warehouse.rb, test/dummy/app/models/widget.rb, test/dummy/app/models/widget_query.rb, test/elastic_record/index/documents_test.rb, test/elastic_record/index/mapping_type_test.rb, test/elastic_record/model_test.rb
Unfortunately, I had missed a bit where the bulk api in ES6 requires type parameters hard stop. (You can provide them in the routing as well). Teaches me to not run the tests on both versions 🤦‍♂️.
~I'm not committed to merging this. elastic_record 5.6.0 can run in both versions (ES6.X & 7.X) though it will produce more deprecation warnings in 7.X.~ Feeling much better about where this is going. We can mostly get rid of mapping_type entirely just hard code '_doc' where appropriate now.
=> Add es6 mode; use _type in bulk requests

lib/elastic_record/index/documents.rb
Elasticsearch changed this path in 7 to /{index}/_update/{id}
Resolves the deprecation warning:
```
[types removal] Specifying types in document update requests is deprecated, use the endpoint /{index}/_update/{id} instead.
```
=> Use new update api path

lib/elastic_record/as_document.rb, test/elastic_record/as_document_test.rb
**Problem**
#107 introduced a regression where inner object fields being set to nil were not being indexed as null.
**Solution**
Ensure all mapped fields are always specified for every inner object, whether the root document is being wholly- or partially-indexed.
=> Ensure that nested objects are fully indexed when a root document is partially updated

lib/elastic_record/as_document.rb, test/dummy/app/models/mock_model.rb, test/dummy/app/models/widget_query.rb, test/elastic_record/as_document_test.rb, test/elastic_record/callbacks_test.rb
**Problem**
#111 accidentally introduced behavior where nested definitions were also being fully index when the parent document was being partially updated.
**Solution**
Ensure that only objects are fully indexed during a partial update, not nested types.
=> Fix nested object indexing

lib/elastic_record/as_document.rb, lib/elastic_record/from_search_hit.rb, test/elastic_record/as_document_test.rb
[Basecamp TODO](https://3.basecamp.com/4119850/buckets/9653296/todos/2293987115)
Elastic Record checks for ranges with Float::INFINITY as their upper bounds. However, content system no longer uses ranges with Float::INFINITY as the upper bound.
Remove handlers for ranges with Float::INFINITY as the upper bound.
This is in use by content system on QA3.
=> Use ruby 2.6 boundless ranges

README.md
The link to this file in the Arelastic gem is broken.
@matthuhiggins - is there a new place this link should point? I was uncertain looking at the Arelastic source in `lib/arelastic/builders/`.
=> Remove Arelastic link

lib/elastic_record/config.rb, test/elastic_record/config_test.rb
See https://github.com/data-axle/content_system/pull/5254#discussion_r490365856
We have no way of backtracking from index alias to model name.
Provide a way.
=> Define method to get model name via index alias

README.md, lib/elastic_record/tasks/index.rake
This change will allow content_system's `bin/setup` to be idempotent, as Rails intended for it to be.
=> Add rake task to create indexes idempotently

lib/elastic_record/index/deferred.rb, lib/elastic_record/index/search.rb
scroll_id can be large depending on shards.
Move to the body of a post request according to https://stackoverflow.com/questions/63587243/scroll-id-returned-by-scroll-api-is-too-long
=> Move scroll_id to a post request

.github/workflows/ruby.yml, test/elastic_record/log_subscriber_test.rb
In recent versions of ES API calls that don't take a body will error when passed a body.
See https://github.com/elastic/elasticsearch/issues/69532
Passing a search request allows a body.
=> Update ES version to more recent version

lib/elastic_record.rb, lib/elastic_record/model/as_document.rb, lib/elastic_record/model/callbacks.rb, lib/elastic_record/model/elastic_connection.rb, lib/elastic_record/model/from_search_hit.rb, lib/elastic_record/model/searching.rb
Before adding a new module to be extended by `ElasticRecord::Model`, I decided to move all existing modules that are extended/includes by `ElasticRecord::Model` into the `ElasticRecord::Model` namespace.
To ease the review, I split this PR into 2 commits: 1 with the namespace change, and another with only whitespace changes.
=> Scope model includes

README.md, elastic_record.gemspec, lib/elastic_record.rb, lib/elastic_record/index/documents.rb, lib/elastic_record/index/manage.rb, lib/elastic_record/model.rb, lib/elastic_record/model/joining.rb, lib/elastic_record/relation.rb, lib/elastic_record/relation/hits.rb, test/elastic_record/integration/active_record_test.rb, test/elastic_record/model/joining_test.rb, test/elastic_record/relation/batches_test.rb, test/elastic_record/searching_test.rb
[INFO-9454](https://infogroup.atlassian.net/browse/INFO-9454)
[ElasticSearch Reference](https://www.elastic.co/guide/en/elasticsearch/reference/current/parent-join.html)
Note that this depends on [the latest arelastic PR](https://github.com/matthuhiggins/arelastic/pull/33).  I have requested a new release from the maintainer after which I will update the gemspec here to require the latest version.
@matthinea I was able to preserve your commit that renamed `parent` => `routing` without making any changes to that file.
=> Support parent-child joins

elastic_record.gemspec
No real changes, just getting the latest version Arelastic has on RubyGems and in its gemspec
=> Bump required version of arelastic

README.md, lib/elastic_record/model/joining.rb
The interface to `has_es_children` is a little cumbersome. Most users won't require complex nestings and will only want to specify a single child or two.
Support passing an instance of `Class` as the `children` argument to `has_es_children`. `README` has examples.
=> Support simpler `has_es_children` input

README.md, lib/elastic_record/model/joining.rb, lib/elastic_record/relation.rb, lib/elastic_record/relation/hits.rb, lib/elastic_record/relation/search_methods.rb
Until now, when querying indices that contain parent-child joins,
we were retriving records of multiple types and then filtering
down to the type we were interesteed in on the client-side after
retrieving results.
This was inefficient.  Going forward, we will filter server-side.
=> Filter by join type

lib/elastic_record/relation.rb, lib/elastic_record/relation/search_methods.rb
By appending the join-type query to filter_values, we were getting mutually exclusive terms.
=> Filter queries by join type without changing the state of the object

lib/elastic_record/relation.rb, test/elastic_record/relation_test.rb
[JIRA](https://infogroup.atlassian.net/browse/INFO-9864)
**Problem:**
When ElasticRecord::Relation loads results #find_hits is called, which takes the IDs from ElasticSearch and calls `Model.find`. This results in an `ActiveRecord::RecordNotFound` error if Elastic has IDs that do not exist in Postgres.
**Solution:**
Add the ability to load the Relation's records without erroring on missing IDs. We could make this the default behavior for `find_hits`, but I'm concerned that will have larger repercussions (result order tests fail when defaulting to where instead of find), so initially this can be enabled where needed (I.E. for submissions).
=> Add ability to safe load relation records

lib/elastic_record/relation/search_methods.rb, test/dummy/app/models/mother.rb, test/dummy/app/models/son.rb, test/elastic_record/model/joining_test.rb, test/elastic_record/relation/search_methods_test.rb
We're filtering by join field in `build_filter_nodes`. But calls to that method from `not` and `nested` result in negated and nested versions of that query, respectively.
Don't add that field when negating. It'll still get added by the initial call to `filter`, as the tests show.
=> Fix nested & negated queries for models with joins

lib/elastic_record/connection.rb, lib/elastic_record/errors.rb
This will make it easier to debug when a ConnectionError occurs.  Most often, these errors occur because of an invalid request being sent to the server.
[Example HB](https://app.honeybadger.io/projects/1671/faults/53816528)
=> Include Request payload in error message for ConnectionErrors

lib/elastic_record/model.rb, lib/elastic_record/model/joining.rb, test/elastic_record/model/joining_test.rb
We'll frequently keep having to check if a place has an ES root before asking for it. Instead, why don't we just make roots the roots of themselves?
Make it so.
=> Define es_root everywhere

lib/elastic_record/relation.rb, lib/elastic_record/relation/search_methods.rb
`includes` and other AR methods cause `Relation` instances to lose their `@safe` values.
Define a method to instantiate a new relation with a new class, and use it when `includes` is called. Make it public facing, for good measure.
=> Define `metamorphose`, which initiates the same relation with a new class

lib/elastic_record/model/as_document.rb
Keyword argument name reflects developer intention rather than functional impact.
Rename it.
=> Change kwarg name to better reflect function

test/elastic_record/index/pagination_test.rb, test/elastic_record/index/scrolling_test.rb
I split up a module into 2 modules following [this comment](https://github.com/data-axle/elastic_record/pull/157#discussion_r873898745), but I forgot to split up the tests.
Also split up the tests.
=> Move scrolling tests to their own file

test/elastic_record/index/documents_test.rb, test/elastic_record/index/pagination_test.rb, test/helper.rb
We have an established, not-polluting way of disabling deferring for a test, but we're not using it everywhere.
Move the helper method to `test_helper.rb` and use it everywhere.
=> Safer way to disable deferring during testing

lib/elastic_record/errors.rb, lib/elastic_record/index/deferred.rb, lib/elastic_record/index/pagination.rb, lib/elastic_record/index/search_after.rb, test/elastic_record/index/pagination_test.rb
Part of https://infogroup.atlassian.net/browse/INFO-9681
`search_after` is too aggressive in its auto-management of PITs. When a PIT ID it's attempting to use is expired, it generates a new one and uses that. This means that records could appear twice in a single call to `search_after`.
Error when `search_after` is attempting to use a PIT ID that's expired.
=> Error when `search_after` attempts to use an expired point-in-time

lib/elastic_record/index/documents.rb, test/elastic_record/index/documents_test.rb
- `delete_by_query` doesn't support deleting documents that require `routing` to be specified.
- `delete_document` improperly specifies query params when a `routing` value is specified.
Fix 'em.
=> Fix deletion with routing

lib/elastic_record/relation.rb, test/elastic_record/relation_test.rb
[JIRA](https://infogroup.atlassian.net/browse/INFO-10493)
Making a relation `safe` removes any ordering within the query, instead orders based on database internal ordering. 
Resort the results from the database based on that from Elastic. 
This is demonstrated in data-axle/content_system#6982
=> preserve order of records when doing safe query

lib/elastic_record/relation.rb, lib/elastic_record/relation/none.rb, test/elastic_record/relation/none_test.rb, test/elastic_record/relation_test.rb
This will enable lines such as [this one](https://github.com/data-axle/content_system/blob/a254ab91b15b7b40fb240def24e1e76d88d66b9f/app/models/lookups/pruner.rb#L28) to look a little nicer.
=> Define `exists?` methods to mimic ActiveRecord

elastic_record.gemspec, lib/elastic_record/connection.rb, lib/elastic_record/index/documents.rb
**Problem:**
`ActiveSupport::TimeWithZone` objects do not get serialized in ISO8601 format when using JSON.generate. Use of Oj has hidden this deficiency previously.
**Solution:**
Use ActiveSupport JSON encoding when generation data for elastic search requests.
=> Use ActiveSupport to encode JSON

Gemfile, Gemfile.lock, elastic_record.gemspec, lib/elastic_record/relation/search_methods.rb, lib/elastic_record/relation/value_methods.rb, test/elastic_record/relation/search_methods_test.rb
No native support for query-time runtime mappings. These are useful for obvious reasons. See [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/runtime-search-request.html#runtime-search-request).
Support them.
=> Add native support for runtime mappings

lib/elastic_record/index/documents.rb, test/elastic_record/index/documents_test.rb
Right now,`Widget.elastic_index.bulk do` block returns 'nil`. If I want to return a value from within it, I have to do something like this:
```
saved_widgets = [].tap do |saved_widgets|
Widget.elastic_index.bulk do
saved_widgets.concat(widget.filter(&:save))
end
end
```
The proposed change fixes `ElasticRecord::Index#start_new_bulk_batch` to return the value returned from the `yield`ed block making the following code possible:
```
saved_widgets = Widget.elastic_index.bulk do
widget.filter(&:save)
end
```
=> Return block's return value from Index#bulk

lib/elastic_record/relation.rb, lib/elastic_record/relation/search_methods.rb, lib/elastic_record/relation/value_methods.rb
On #147 @j1wilmot added support for `safe` and #153 @matthinea added metamorphose to copy the value of `@safe` to a newly created Relation. Relation already has support for this as part of `*_value` methods defined with `SINGLE_VALUE_METHODS`. These methods are set on the `values` hash and copied to the new object when an active record method is called.
* Defined `:safe` on `SINGLE_VALUE_METHODS`
* Move definition of `safe!` and `safe?` to `SearchMethods`
* Clone relations with klass.new
P.S. Howdy guys! I was reading through the repo and saw this little bike shed.
=> Clone shared search values with *VALUE_METHODS

lib/elastic_record/model/from_search_hit.rb, test/elastic_record/from_search_hits_test.rb
If `from_search_hit` is passed a hit in an `inner_hits` object, the resulting instantiated object will have the ID of the parent object rather than the ID of the nested object returned by `inner_hits`. This is because the `_id` of `inner_hit` hits is the ID of the top-level "parent" document.
For example, consider an index of "place" documents where each place has nested "location_intents" documents. A hit in the `inner_hits` `hits` array will look like this:
```
{
"_index" : "places",
"_type" : "_doc",
"_id" : "761522765",
"_nested" : {
"field" : "location_intents",
"offset" : 4
},
"_score" : 3.459679,
"_source" : {
"score" : 65.0,
"topic_ids" : [
"f5d7ec74b5",
"22d32051bd",
"1a9bf45c5d"
],
"vendor_id" : "888",
"id" : "4528bd6f82a1489aa3aab1e09e6e7b67"
}
}
```
When passed this object, …
=> Use source ID as object ID when present
